### ISSUE TITLE
Faces don't import correctly

### ISSUE THREAD

**Issue by CelestialRiot** [Befzz/blender3d_import_psk_psa#46]
Using 2.8 with latest add-on, some models important correct, but some had incorrect face connections.

https://imgur.com/a/rlCe3DJ

**Comment by Blenux** [comment]
Think it might be the way you retrieved the model, if talking about Brimstone from Valorant?

https://i.imgur.com/i1MmymM.png

**Comment by Befzz** [comment]
please, share .psk file 😊

**Comment by ItzAresLP** [comment]
I'm having the same issue using the 'charselect model' of brimstone, which is a more rigged version of the in-game brimstone.

_Issue image:_
https://imgur.com/a/Lpnjru0
_psk download link:_
https://drive.google.com/file/d/1HBTbEBoizLanFY2AzckoT2XVPyWQq1lh/view?usp=sharing

**Comment by Befzz** [comment]
issue was fixed time ago, but in "latest branch"  

now "master" = "latest"  

redownload plugin please  
https://raw.githubusercontent.com/Befzz/blender3d_import_psk_psa/latest/addons/io_import_scene_unreal_psa_psk_280.py

**Comment by ItzAresLP** [comment]
oh, i thought this issue would still exist, since it's labeled as 'open'. But thank you for your quick response and your continuously work!
